name: CLI Deploy
on:
  workflow_dispatch:
    inputs:
      context_dir:
        description: 'Context dir'
        required: true
        default: 'nodejs-express'
        type: choice
        options:
          - angular
          - go-sample-api
          - java-springboot
          - nextjs
          - nodejs-express
          - nodejs-express-metrics
          - nodejs-express-with-webpack
          - nodejs-express-with-webpack-and-postgres
          - python-django
          - vue
      env_name:
        description: 'Env name'
        required: true
        type: string
jobs:
  DeployApp:
    runs-on: ubuntu-latest
    container:
      image: zcloudws/zcloud-cli
      env:
        ZCLOUD_USER_TOKEN: ${{ secrets.ZCLOUD_USER_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Deploy with zCloud CLI
        env:
          ZCLOUD_USER_TOKEN: ${{ secrets.ZCLOUD_USER_TOKEN }}
        run: zcloud deploy --env ${{ inputs.env_name }} --dir "${{ inputs.context_dir }}"
